/* Generated by cbindgen — do not edit */

#ifndef AWALTERMINAL_H
#define AWALTERMINAL_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an ACP client.
 */
typedef struct ATAcpClient ATAcpClient;

/**
 * Opaque handle to a terminal surface.
 */
typedef struct ATSurface ATSurface;

/**
 * A complete recording that can be saved/loaded.
 */
typedef struct Recording Recording;

/**
 * C-compatible cell for FFI transfer.
 */
typedef struct CCell {
    uint32_t codepoint;
    uint8_t fg_r;
    uint8_t fg_g;
    uint8_t fg_b;
    uint8_t fg_a;
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
    uint8_t bg_a;
    uint16_t attrs;
} CCell;

/**
 * Search result entry.
 */
typedef struct ATSearchResult {
    uint32_t col;
    int32_t row;
} ATSearchResult;

/**
 * C-compatible output region for FFI transfer.
 */
typedef struct COutputRegion {
    int32_t start_row;
    int32_t end_row;
    uint8_t region_type;
    uint8_t collapsed;
    uint32_t line_count;
    char *label;
} COutputRegion;

/**
 * C-compatible region summary for the side panel.
 */
typedef struct CRegionSummary {
    uint32_t tool_use_count;
    uint32_t code_block_count;
    uint32_t thinking_count;
    uint32_t diff_count;
    uint32_t file_ref_count;
} CRegionSummary;

/**
 * C-compatible ACP event.
 * event_type: 0=Initialized, 1=SessionCreated, 2=TextChunk, 3=ToolCall,
 *             4=ToolCallUpdate, 5=TurnEnd, 6=Error, 7=ProcessExited,
 *             8=PermissionRequest, 9=Cancelled, 10=AuthRequired,
 *             11=FsReadRequest, 12=FsWriteRequest, 13=SubagentSpawned,
 *             14=SubagentProgress, 15=SubagentComplete, 16=SubagentError,
 *             17=Stderr, 18=ProtocolLog, 27=TerminalCreate, 28=TerminalOutput,
 *             29=TerminalWaitForExit, 30=TerminalKill, 31=TerminalRelease
 */
typedef struct ATAcpEvent {
    uint8_t event_type;
    char *text;
    char *text2;
} ATAcpEvent;

/**
 * A single diff line exposed to C.
 */
typedef struct ATDiffLine {
    uint8_t kind;
    char *content;
} ATDiffLine;

/**
 * A parsed diff hunk exposed to C.
 */
typedef struct ATDiffHunk {
    char *header;
    uint32_t old_start;
    uint32_t old_count;
    uint32_t new_start;
    uint32_t new_count;
    struct ATDiffLine *lines;
    uint32_t line_count;
} ATDiffHunk;

/**
 * Parsed diff result.
 */
typedef struct ATDiffResult {
    struct ATDiffHunk *hunks;
    uint32_t hunk_count;
} ATDiffResult;

/**
 * C-compatible region for FFI.
 */
typedef struct CRecordedRegion {
    int32_t start_row;
    int32_t end_row;
    uint8_t region_type;
    char *label;
} CRecordedRegion;

/**
 * C-compatible frame snapshot for FFI reads.
 */
typedef struct CFrameSnapshot {
    uint64_t timestamp_ms;
    uint32_t cursor_row;
    uint32_t cursor_col;
    bool cursor_visible;
    uint32_t region_count;
} CFrameSnapshot;

/**
 * Create a new terminal surface with the given dimensions.
 */
struct ATSurface *at_surface_new(uint32_t cols,
                                 uint32_t rows);

/**
 * Terminate the child process (PTY) without destroying the surface.
 * Safe to call multiple times — subsequent calls are no-ops.
 */
void at_surface_terminate(struct ATSurface *surface);

/**
 * Destroy a terminal surface.
 */
void at_surface_destroy(struct ATSurface *surface);

/**
 * Spawn a shell process. Returns 0 on success, -1 on failure.
 */
int32_t at_surface_spawn_shell(struct ATSurface *surface,
                               const char *shell);

/**
 * Spawn a shell running a specific command. Returns 0 on success, -1 on failure.
 * The shell is invoked as a login shell with `-c command`.
 */
int32_t at_surface_spawn_command(struct ATSurface *surface,
                                 const char *shell,
                                 const char *command);

/**
 * Get the PTY master file descriptor (for polling).
 */
int at_surface_get_fd(const struct ATSurface *surface);

/**
 * Get the child shell PID.
 */
int32_t at_surface_get_child_pid(const struct ATSurface *surface);

/**
 * Read from the PTY and process VT sequences. Returns number of bytes read, 0 if nothing available, -1 on error.
 */
int32_t at_surface_process_pty(struct ATSurface *surface);

/**
 * Send a key event (raw bytes) to the PTY.
 */
int32_t at_surface_key_event(struct ATSurface *surface,
                             const uint8_t *data,
                             uint32_t len);

/**
 * Queue data for asynchronous writing to the PTY.
 * Returns 0 on success, -1 if surface/data is invalid.
 */
int32_t at_surface_queue_write(struct ATSurface *surface,
                               const uint8_t *data,
                               uint32_t len);

/**
 * Drain pending writes to the PTY. Returns bytes written, 0 if nothing pending, -1 on error.
 */
int32_t at_surface_drain_writes(struct ATSurface *surface);

/**
 * Check if there are pending writes in the queue.
 */
bool at_surface_has_pending_writes(const struct ATSurface *surface);

/**
 * Get the screen dimensions.
 */
void at_surface_get_size(const struct ATSurface *surface,
                         uint32_t *cols,
                         uint32_t *rows);

/**
 * Resize the terminal surface (screen grid + PTY).
 */
void at_surface_resize(struct ATSurface *surface,
                       uint32_t cols,
                       uint32_t rows);

/**
 * Read cells from the screen into the provided buffer (viewport-aware).
 * Buffer must have space for (cols * rows) CCells.
 * Returns the number of cells written.
 */
uint32_t at_surface_read_cells(const struct ATSurface *surface,
                               struct CCell *out,
                               uint32_t max_cells);

/**
 * Get cursor position.
 */
void at_surface_get_cursor(const struct ATSurface *surface,
                           uint32_t *row,
                           uint32_t *col,
                           bool *visible);

/**
 * Check if screen content has changed since last check. Resets the dirty flag.
 */
bool at_surface_is_dirty(struct ATSurface *surface);

/**
 * Get the current kitty keyboard protocol flags (0 = legacy mode).
 */
uint32_t at_surface_get_kitty_keyboard_flags(const struct ATSurface *surface);

/**
 * Check if synchronized output mode (mode 2026) is active.
 * When active, the caller should defer rendering until the mode is reset.
 */
bool at_surface_is_synchronized(const struct ATSurface *surface);

/**
 * Feed raw bytes directly into the VT parser (no PTY needed).
 * Used for rendering TUI menus before a shell is spawned.
 */
void at_surface_feed_bytes(struct ATSurface *surface,
                           const uint8_t *data,
                           uint32_t len);

/**
 * Initialize logging (call once at startup).
 */
void at_init_logging(void);

/**
 * Set a palette color (index 0-255) to an RGB value.
 */
void at_surface_set_palette_color(struct ATSurface *surface,
                                  uint8_t index,
                                  uint8_t r,
                                  uint8_t g,
                                  uint8_t b);

/**
 * Set the default foreground color used when a cell has Color::Default.
 */
void at_surface_set_default_fg(struct ATSurface *surface,
                               uint8_t r,
                               uint8_t g,
                               uint8_t b);

/**
 * Set the default background color used when a cell has Color::Default.
 */
void at_surface_set_default_bg(struct ATSurface *surface,
                               uint8_t r,
                               uint8_t g,
                               uint8_t b);

/**
 * Scroll the viewport by delta lines. Positive = scroll up (into history).
 */
void at_surface_scroll_viewport(struct ATSurface *surface,
                                int32_t delta);

/**
 * Get current viewport offset (0 = live, >0 = scrolled into history).
 */
int32_t at_surface_get_viewport_offset(const struct ATSurface *surface);

/**
 * Get scrollback buffer length.
 */
int32_t at_surface_get_scrollback_len(const struct ATSurface *surface);

/**
 * Start a selection at grid position.
 */
void at_surface_start_selection(struct ATSurface *surface,
                                uint32_t col,
                                int32_t row);

/**
 * Update selection endpoint.
 */
void at_surface_update_selection(struct ATSurface *surface,
                                 uint32_t col,
                                 int32_t row);

/**
 * Set rectangular (block) selection mode.
 */
void at_surface_set_rectangular_selection(struct ATSurface *surface,
                                          bool rectangular);

/**
 * Clear the selection.
 */
void at_surface_clear_selection(struct ATSurface *surface);

/**
 * Get selected text. Returns a C string that must be freed with `at_free_string`.
 */
char *at_surface_get_selected_text(const struct ATSurface *surface);

/**
 * Free a string returned by FFI functions.
 */
void at_free_string(char *s);

/**
 * Get the current mouse tracking mode (0=none, 1=click, 2=button/drag, 3=any).
 */
int32_t at_surface_get_mouse_mode(const struct ATSurface *surface);

/**
 * Check if SGR mouse mode (1006) is enabled.
 */
bool at_surface_get_sgr_mouse(const struct ATSurface *surface);

/**
 * Check if bracketed paste mode is enabled.
 */
bool at_surface_get_bracketed_paste(const struct ATSurface *surface);

/**
 * Get the terminal title. Returns a C string that must be freed with `at_free_string`.
 */
char *at_surface_get_title(const struct ATSurface *surface);

/**
 * Get the working directory (from OSC 7). Returns a C string that must be freed with `at_free_string`.
 */
char *at_surface_get_working_directory(const struct ATSurface *surface);

/**
 * Get the hyperlink URL for a cell at the given viewport position.
 * Returns null if no hyperlink. Caller must free with `at_free_string`.
 */
char *at_surface_get_hyperlink(const struct ATSurface *surface,
                               uint32_t col,
                               uint32_t row);

/**
 * Search scrollback + screen for a query string.
 * Writes results into `out`, returns the number of results written (up to max_results).
 */
uint32_t at_surface_search(const struct ATSurface *surface,
                           const char *query,
                           struct ATSearchResult *out,
                           uint32_t max_results);

/**
 * Enable or disable AI output analysis for this surface.
 */
void at_surface_set_ai_analysis(struct ATSurface *surface,
                                bool enabled);

/**
 * Set the AI provider for this surface (enables provider-specific tool detection).
 */
void at_surface_set_ai_provider(struct ATSurface *surface,
                                const char *provider);

/**
 * Check if AI analysis is enabled.
 */
bool at_surface_get_ai_analysis(const struct ATSurface *surface);

/**
 * Get the number of detected regions.
 */
uint32_t at_surface_get_region_count(const struct ATSurface *surface);

/**
 * Read detected regions into the provided buffer.
 * Buffer must have space for at least `max_regions` COutputRegion entries.
 * Returns the number of regions written.
 * Caller must free each label with `at_free_string`.
 */
uint32_t at_surface_get_regions(const struct ATSurface *surface,
                                struct COutputRegion *out,
                                uint32_t max_regions);

/**
 * Toggle fold/collapse state for the region containing the given row.
 * Returns true if a region was found and toggled.
 */
bool at_surface_toggle_fold(struct ATSurface *surface,
                            int32_t row);

/**
 * Get a summary of detected regions (counts by type).
 */
void at_surface_get_region_summary(const struct ATSurface *surface,
                                   struct CRegionSummary *out);

/**
 * Get a file reference by index from the region summary.
 * Returns a C string that must be freed with `at_free_string`.
 */
char *at_surface_get_file_ref(const struct ATSurface *surface,
                              uint32_t index);

/**
 * Check if remote control mode has been detected.
 */
bool at_surface_is_remote_control_active(const struct ATSurface *surface);

/**
 * Get the remote control session URL. Returns a C string that must be freed with `at_free_string`, or null.
 */
char *at_surface_get_remote_control_url(const struct ATSurface *surface);

/**
 * Clear remote control state.
 */
void at_surface_clear_remote_control(struct ATSurface *surface);

/**
 * Manually trigger AI analysis (e.g. after scrollback changes without PTY activity).
 */
void at_surface_analyze(struct ATSurface *surface);

/**
 * Get the current input line (text before cursor). Returns a C string that must be freed with `at_free_string`.
 */
char *at_surface_get_input_line(const struct ATSurface *surface);

/**
 * Poll next event. Returns null if no event available.
 * Caller must free with at_acp_free_event.
 */
struct ATAcpEvent *at_acp_poll_event(struct ATAcpClient *client);

/**
 * Send a text prompt. Returns 0 on success, -1 on error.
 */
int32_t at_acp_send_prompt(struct ATAcpClient *client,
                           const char *text);

/**
 * Cancel current operation. Returns 0 on success, -1 on error.
 */
int32_t at_acp_cancel(struct ATAcpClient *client);

/**
 * Cancel a specific subagent. Returns 0 on success, -1 on error.
 */
int32_t at_acp_cancel_subagent(struct ATAcpClient *client,
                               const char *subagent_id);

/**
 * Rewind session to previous turn. Returns 0 on success, -1 on error.
 */
int32_t at_acp_send_rewind(struct ATAcpClient *client);

/**
 * Send session/close notification. Returns 0 on success, -1 on error.
 */
int32_t at_acp_send_close(struct ATAcpClient *client);

/**
 * Request session list. Returns 0 on success, -1 on error.
 */
int32_t at_acp_send_list_sessions(struct ATAcpClient *client);

/**
 * Respond to a permission request. Returns 0 on success, -1 on error.
 */
int32_t at_acp_respond_permission(struct ATAcpClient *client,
                                  uint64_t request_id,
                                  bool approved);

/**
 * Respond to a fs/read_text_file request. Pass null content_ptr for error.
 */
int32_t at_acp_respond_fs_read(struct ATAcpClient *client,
                               uint64_t request_id,
                               const char *content_ptr);

/**
 * Respond to a fs/write_text_file request.
 */
int32_t at_acp_respond_fs_write(struct ATAcpClient *client,
                                uint64_t request_id,
                                bool success);

/**
 * Send an arbitrary JSON result for a server-to-client request.
 */
int32_t at_acp_respond_json(struct ATAcpClient *client,
                            uint64_t request_id,
                            const char *json);

/**
 * Send a JSON-RPC error response for a server-to-client request.
 */
int32_t at_acp_respond_error(struct ATAcpClient *client,
                             uint64_t request_id,
                             int64_t code,
                             const char *message);

/**
 * Get the current ACP state. Returns: 0=Initializing, 1=Ready, 2=Prompting, 3=Dead, 4=Recovering.
 */
uint8_t at_acp_get_state(const struct ATAcpClient *client);

/**
 * Free an event returned by at_acp_poll_event.
 */
void at_acp_free_event(struct ATAcpEvent *event);

/**
 * Get the active session ID. Returns null if no session. Caller must free with `at_free_string`.
 */
char *at_acp_get_session_id(const struct ATAcpClient *client);

/**
 * Force-kill: signals the ACP state machine for hard termination.
 * Caller is responsible for terminating the actual process.
 */
void at_acp_force_kill(struct ATAcpClient *client);

/**
 * Create an ACP client that only writes to stdin (reading handled by caller).
 * Returns opaque handle or null on failure.
 */
struct ATAcpClient *at_acp_create_writer(int32_t stdin_fd);

/**
 * Feed a line of stdout to the ACP client for JSON-RPC parsing.
 */
void at_acp_feed_line(struct ATAcpClient *client,
                      const char *line);

/**
 * Set the session ID to resume after initialization.
 */
void at_acp_set_resume_session(struct ATAcpClient *client,
                               const char *session_id);

/**
 * Set the working directory for session/new and session/resume requests.
 */
void at_acp_set_cwd(struct ATAcpClient *client,
                    const char *cwd);

/**
 * Destroy the ACP client and free all resources.
 * Caller is responsible for terminating the actual process beforehand.
 */
void at_acp_destroy(struct ATAcpClient *client);

/**
 * Parse a unified diff into hunks. Caller must free with `at_acp_free_diff_result`.
 */
struct ATDiffResult *at_acp_parse_diff(const char *diff_text);

/**
 * Apply selected hunks to original content. Returns new content string (caller frees with `at_free_string`).
 */
char *at_acp_apply_hunks(const char *original,
                         const char *diff_text,
                         const bool *accepted,
                         uint32_t accepted_count);

/**
 * Free a diff result returned by `at_acp_parse_diff`.
 */
void at_acp_free_diff_result(struct ATDiffResult *result);

/**
 * Create a new recording.
 */
struct Recording *at_recording_new(uint32_t cols,
                                   uint32_t rows,
                                   const char *model,
                                   const char *path);

/**
 * Add a frame to the recording.
 */
void at_recording_add_frame(struct Recording *recording,
                            const struct CCell *cells,
                            uint32_t count,
                            uint32_t cursor_row,
                            uint32_t cursor_col,
                            bool cursor_visible,
                            const struct CRecordedRegion *regions,
                            uint32_t region_count,
                            uint64_t timestamp_ms);

/**
 * Get the number of frames in the recording.
 */
uint32_t at_recording_frame_count(const struct Recording *recording);

/**
 * Get a frame's cells and metadata.
 * Writes cells into `out_cells` (must have space for cols*rows cells)
 * and metadata into `out_snapshot`.
 * Returns true on success.
 */
bool at_recording_get_frame(const struct Recording *recording,
                            uint32_t index,
                            struct CCell *out_cells,
                            struct CFrameSnapshot *out_snapshot);

/**
 * Save the recording to a file. Returns 0 on success, -1 on failure.
 */
int32_t at_recording_save(const struct Recording *recording,
                          const char *path);

/**
 * Load a recording from a file. Returns null on failure.
 */
struct Recording *at_recording_load(const char *path);

/**
 * Destroy a recording.
 */
void at_recording_destroy(struct Recording *recording);

/**
 * Get the grid dimensions of a recording.
 */
void at_recording_get_size(const struct Recording *recording,
                           uint32_t *cols,
                           uint32_t *rows);

#endif  /* AWALTERMINAL_H */
